// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofutrsieokzfvypdoeen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mdXRyc2llb2t6ZnZ5cGRvZWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTQ0OTcsImV4cCI6MjA3MTc3MDQ5N30.N7elAdkxhFxBkgjHZqxilwd-IfuudQK1fyA-87W2Axw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});